const LibInfoData = () => {
  return {
    "공공도서관": {
      "단원구": {
        "중앙도서관": {
          name: "중앙도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-2703",
          address: "안산시 단원구 안산천남로 14",
          homepage: "https://lib.ansan.go.kr/jungang",
          map: "https://kko.to/ZsHw3hcrpS",
          xloc: 373,
          yloc: 248,
        },
        "단원어린이도서관": {
          name: "단원어린이도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-2678",
          address: "안산시 단원구 화정로 30",
          homepage: "https://lib.ansan.go.kr/danwon",
          map: "https://kko.to/mWyVHzZonC",
          xloc: 372,
          yloc: 167,
        },
        "관산도서관": {
          name: "관산도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-2751",
          address: "안산시 단원구 관산길290",
          homepage: "https://lib.ansan.go.kr/gwansan",
          map: "https://kko.to/T8ELlFkD7D",
          xloc: 337,
          yloc: 167,
        },
        "원고잔도서관": {
          name: "원고잔도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-3876",
          address: "안산시 단원구 원고잔공원로 33",
          homepage: "https://lib.ansan.go.kr/wongojan",
          map: "https://kko.to/H-yNgOyjyX",
          xloc: 410,
          yloc: 168,
        },
        "대부도서관": {
          name: "대부도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-3958",
          address: "경기 안산시 단원구 대남로 30",
          homepage: "https://lib.ansan.go.kr/daebu",
          map: "https://kko.to/oR0HTz91fc",
          xloc: 92,
          yloc: 282,
        },
        "선부도서관": {
          name: "선부도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-3888",
          address: "경기도 안산시 단원구 선부동 1068번지",
          homepage: "https://lib.ansan.go.kr/seonbu",
          map: "https://kko.to/NlUuspMoa9",
          xloc: 352,
          yloc: 132,
        },
        "미디어도서관": {
          name: "미디어도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-3348",
          address: "경기도 안산시 단원구 광덕1로 198",
          homepage: "https://lib.ansan.go.kr/medialib",
          map: "https://kko.to/8EtJWaAyjY",
          xloc: 405,
          yloc: 215,
        },
      },
      "상록구": {
        "감골도서관": {
          name: "감골도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-2665",
          address: "안산시 상록구 감골공원안길 16-1",
          homepage: "https://lib.ansan.go.kr/gamgol",
          map: "https://kko.to/U2O0dMjj0V",
          xloc: 570,
          yloc: 219,
        },
        "상록어린이도서관": {
          name: "상록어린이도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-2671",
          address: "안산시 상록구 구룡체육관로 45",
          homepage: "https://lib.ansan.go.kr/sangnok",
          map: "https://kko.to/X3yU-OKtW9",
          xloc: 405,
          yloc: 179,
        },
        "수암도서관": {
          name: "수암도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-3967",
          address: "안산시 상록구 원당골1길 23-3",
          homepage: "https://lib.ansan.go.kr/suam",
          map: "https://kko.to/8JgP8NnMYk",
          xloc: 457,
          yloc: 218,
        },
        "성포도서관": {
          name: "성포도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-2757",
          address: "안산시 상록구 충장로 528",
          homepage: "https://lib.ansan.go.kr/seongpo",
          map: "https://kko.to/i1Qye00uJ5",
          xloc: 350,
          yloc: 85,
        },
        "부곡도서관": {
          name: "부곡도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-3603",
          address: "안산시 상록구 성호로 333",
          homepage: "https://lib.ansan.go.kr/bugok",
          map: "https://kko.to/Ubh1dU0ItK",
          xloc: 443,
          yloc: 140,
        },
        "본오도서관": {
          name: "본오도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-3698",
          address: "안산시 상록구 본오동 778번지",
          homepage: "https://lib.ansan.go.kr/bono",
          map: "https://kko.to/ZW43Jq9EJz",
          xloc: 85,
          yloc: 269,
        },
        "반월도서관": {
          name: "반월도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-2663",
          address: "안산시 상록구 반월새싹길 39-3",
          homepage: "https://lib.ansan.go.kr/banwol",
          map: "https://kko.to/bTI59jwKo_",
          xloc: 421,
          yloc: 103,
        },
        "월피예술도서관": {
          name: "월피예술도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-369-1869",
          address: "안산시 상록구 광덕산안길 32",
          homepage: "https://lib.ansan.go.kr/wolpi",
          map: "https://kko.to/t5BHYJdqZg",
          xloc: 571,
          yloc: 221,
        },
        "상록수도서관": {
          name: "상록수도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-2672",
          address: "경기도 안산시 상록구 샘골로 167",
          homepage: "https://lib.ansan.go.kr/sanglocksoo",
          map: "https://kko.to/Y8aDknNkxv",
          xloc: 429,
          yloc: 125,
        },
      },
    },
    "공립작은도서관": {
      "단원구": {
        "신길샛별작은도서관": {
          name: "신길샛별작은도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-492-2707",
          address: "안산시 단원구 신길동 1483",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/233dX3tEK7",
          xloc: 485,
          yloc: 285,
        },
        "선녀마을작은도서관": {
          name: "선녀마을작은도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-411-3784",
          address: "안산시 단원구 우목골길 7-15 3층",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/ZsedpMEvkh",
          xloc: 482,
          yloc: 251,
        },
        "와동별빛누리작은도서관": {
          name: "와동별빛누리작은도서관",
          holyday: "6일, 7일, 13일, 14일, 20일, 21일, 27일, 28일",
          phone: "T. 031-402-7492",
          address: "안산시 단원구 와동로 118",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/UAn43C_gsP",
          xloc: 400,
          yloc: 256,
        },
        "달미작은도서관": {
          name: "달미작은도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-3750",
          address: "경기도 안산시 단원구 선삼로 4안길 25-9",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/GzRyzXraWO",
          xloc: 438,
          yloc: 257,
        },
        "안산다문화작은도서관": {
          name: "안산다문화작은도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-493-2661",
          address: "안산시 단원구 부부로 43",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/bqomyGR2W-",
          xloc: 388,
          yloc: 274,
        },
        "석수골작은도서관": {
          name: "석수골작은도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-439-2707",
          address: "안산시 단원구 선부2동 1159번지 2층",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/bI31UOR2m0",
          xloc: 229,
          yloc: 137,
        },
        "당곡작은도서관": {
          name: "당곡작은도서관",
          holyday: "1일, 8일, 15일, 22일, 29일",
          phone: "T. 031-481-3880",
          address: "안산시 단원구 예술대학로 76",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/GZyeF2eXPa",
          xloc: 387,
          yloc: 83,
        },
        "신길작은도서관": {
          name: "신길작은도서관",
          holyday: "5일, 12일, 19일, 26일",
          phone: "T. 031-481-3833",
          address: "안산시 단원구 신길동 1694",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/h6gi4elHqU",
          xloc: 389,
          yloc: 119,
        },
      },
      "상록구": {
        "안산평생학습관작은도서관": {
          name: "안산평생학습관작은도서관",
          holyday: "7일, 14일, 21일, 28일",
          phone: "T. 070-4492-0796",
          address: "안산시 상록구 차돌배기로 24-1",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/ZsedpMEvkh",
          xloc: 489,
          yloc: 280,
        },
        "사이동꿈을키우는작은도서관": {
          name: "사이동꿈을키우는작은도서관",
          holyday: "1일, 8일, 15일, 16일, 17일, 18일, 19일, 22일, 29일",
          phone: "T. 031-417-2707",
          address: "안산시 상록구 사2동 1472-13번지 2층",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/bzHXSvzy7I",
          xloc: 479,
          yloc: 253,
        },
        "해양동작은도서관": {
          name: "해양동작은도서관",
          holyday: "6일, 7일, 13일, 14일, 20일, 21일, 27일, 28일",
          phone: "T. 031-481-5774",
          address: "안산시 상록구 해양로8",
          homepage: "https://lib.ansan.go.kr/smalllib",
          map: "https://kko.to/bzHXSvzy7I",
          xloc: 403,
          yloc: 259,
        },
      },
    },
    "스마트도서관": {
      "중앙역 스마트도서관": {
        "hidden": {
          name: "중앙역 스마트도서관",
          holyday: "365일 00시 ~ 24시 (02시~04시 시스템 점검)",
          phone: "031-481-3864",
          address: "단원구 중앙대로 918",
          homepage: "",
          map: "https://kko.to/xbdMzmy_HF",
          xloc: 402,
          yloc: 206,
        },

      },
      "상록수역 스마트도서관": {
        "hidden": {
          name: "상록수역 스마트도서관",
          holyday: "365일 00시 ~ 24시 (02시~04시 시스템 점검)",
          phone: "031-481-3864",
          address: "상록구 상록수로 61",
          homepage: "",
          map: "https://kko.to/lNrfezg1MU",
          xloc: 462,
          yloc: 240,
        },
      },
      "한대앞역 스마트도서관": {
        "hidden": {
          name: "한대앞역 스마트도서관",
          holyday: "365일 00시 ~ 24시 (02시~04시 시스템 점검)",
          phone: "031-481-3864",
          address: "상록구 충장로 337",
          homepage: "",
          map: "https://kko.to/gdNmJfiqjx",
          xloc: 442,
          yloc: 220,
        },
      },
      "선부역 스마트도서관": {
        "hidden": {
          name: "선부역 스마트도서관",
          holyday: "365일 00시 ~ 24시 (02시~04시 시스템 점검)",
          phone: "031-481-3864",
          address: "단원구 선부동 1074-1",
          homepage: "",
          map: "https://kko.to/mh7Udq48zX",
          xloc: 383,
          yloc: 185,
        },
      },
      "고잔뜰 스마트도서관": {
        "hidden": {
          name: "고잔뜰 스마트도서관",
          holyday: "365일 00시 ~ 24시 (02시~04시 시스템 점검)",
          phone: "031-481-3864",
          address: "홈플러스앞 고잔뜰먹거리타운 18320번 버스정류장",
          homepage: "",
          map: "https://kko.to/j9O6vnF_PK",
          xloc: 403,
          yloc: 193,
        },
      },
      "단원구청 스마트도서관": {
        "hidden": {
          name: "단원구청 스마트도서관",
          holyday: "월요일 ~ 금요일 09시 ~ 18시 단원구청민원실 운영 시간 내 (공휴일 미운영)",
          phone: "031-481-3864",
          address: "단원구 화랑로 250",
          homepage: "",
          map: "https://kko.to/bhEpbF1dv7",
          xloc: 409,
          yloc: 209,
        },
      },
    },
  };

}

export default LibInfoData;